/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("CommissionDetailObjectPageObjectPage journey");

        opaTest("Navigate to CommissionDetailObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheCommissionDetailListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheCommissionDetailListGenerated.onTable().iCheckRows();
            When.onTheCommissionDetailListGenerated.onTable().iPressRow(0);

            Then.onTheCommissionDetailObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheCommissionDetailObjectPageGenerated.iCheckSection({ section: "GeneralInfo" });
            Then.onTheCommissionDetailObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Bukrs" });
            Then.onTheCommissionDetailObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Fkdat" });
            Then.onTheCommissionDetailObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Vkorg" });
            Then.onTheCommissionDetailObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Zclpr" });
            Then.onTheCommissionDetailObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Zcdaz" });
            Then.onTheCommissionDetailObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Namea" });
            Then.onTheCommissionDetailObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Vbeln" });
            Then.onTheCommissionDetailObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Kunrg" });
            Then.onTheCommissionDetailObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Zimco" });
            Then.onTheCommissionDetailObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Zimmg" });
            Then.onTheCommissionDetailObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Waerk" });
            Then.onTheCommissionDetailObjectPageGenerated.onForm({ section: "GeneralInfo" }).iCheckField({ property: "Zstre" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});